""" Various cursors used by the game """


class Cursors:
    """Main cursor class"""

    def __init__(self):
        self.arrow = (
            "xX                      ",
            "X.X                     ",
            "X..X                    ",
            "X...X                   ",
            "X....X                  ",
            "X.....X                 ",
            "X......X                ",
            "X.......X               ",
            "X........X              ",
            "X.........X             ",
            "X......XXXXX            ",
            "X...X..X                ",
            "X..XX..X                ",
            "X.X XX..X               ",
            "XX   X..X               ",
            "X     X..X              ",
            "      X..X              ",
            "       X..X             ",
            "       X..X             ",
            "        XX              ",
            "                        ",
            "                        ",
            "                        ",
            "                        ",
        )

        self.stop = (
            "                        ",
            "                        ",
            "         XXXXXX         ",
            "       XX......XX       ",
            "      X..........X      ",
            "     X....XXXX....X     ",
            "    X...XX    XX...X    ",
            "   X.....X      X...X   ",
            "   X..X...X      X..X   ",
            "  X...XX...X     X...X  ",
            "  X..X  X...X     X..X  ",
            "  X..X   X...X    X..X  ",
            "  X..X    X.,.X   X..X  ",
            "  X..X     X...X  X..X  ",
            "  X...X     X...XX...X  ",
            "   X..X      X...X..X   ",
            "   X...X      X.....X   ",
            "    X...XX     X...X    ",
            "     X....XXXXX...X     ",
            "      X..........X      ",
            "       XX......XX       ",
            "         XXXXXX         ",
            "                        ",
            "                        ",
        )

        self.move = (
            "                        ",
            "                        ",
            "            X           ",
            "            XX          ",
            "            X X         ",
            "            X..X        ",
            "            X...X       ",
            "            X....X      ",
            " XXXXXXXXXXXX.....X     ",
            " X.................X    ",
            " X..................X   ",
            " X...................x  ",
            " X..................X   ",
            " X.................X    ",
            " XXXXXXXXXXXX.....X     ",
            "            X....X      ",
            "            X...X       ",
            "            X..X        ",
            "            X.X         ",
            "            XX          ",
            "            X           ",
            "                        ",
            "                        ",
            "                        ",
        )
        self.hand = (
            "     xX         ",
            "    X..X        ",
            "    X..X        ",
            "    X..X        ",
            "    X..XXXXX    ",
            "    X..X..X.XX  ",
            " XX X..X..X.X.X ",
            "X..XX.........X ",
            "X...X.........X ",
            " X.....X.X.X..X ",
            "  X....X.X.X..X ",
            "  X....X.X.X.X  ",
            "   X...X.X.X.X  ",
            "    X.......X   ",
            "     X....X.X   ",
            "     XXXXX XX   ",
        )
